version: "3.5"

name: "react-native-components"
services:
    react-native-components:
        image: app:latest
        build: .
        container_name: react-native-components
        volumes:
            - ..:/workspace
            - ~/.npmrc:/home/node/.npmrc
        network_mode: "host"
        env_file: .env
        command: sleep infinity
