version: "3.5"

services:
    react-native-components:
        image: app:latest
        build: .
        container_name: react-native-components
        ports:
            - 19005:19005
        volumes:
            - ..:/home/node/workspace
            - ~/.npmrc:/home/node/.npmrc
        command: sleep infinity
