name: "react-native-components"
services:
    react-native-components:
        image: app:latest
        build: .
        container_name: react-native-components
        volumes:
            - ..:/workspace
            - ~/.npmrc:/home/node/.npmrc
            - ~/.bashrc:/home/node/.bashrc
        network_mode: "host"
        command: sleep infinity
